using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TestGun : MonoBehaviour
{
    [Header("’e")]
    public GameObject m_Bullet;
    [Header("eŒû")]
    public Transform m_Muzzle;

    void Update()
    {
        //”­–Cˆ—
        Fire();
    }
    /// <summary>
    /// ”­–Cˆ—
    /// </summary>
    public void Fire()
    {
        //ƒ}ƒEƒX¶ƒNƒŠƒbƒN
        if(Input.GetMouseButtonDown(0))
        {
            //’e‚ğoŒ»‚³‚¹AeŒû‚ÌÀ•W‚ÆŒü‚«‚É‡‚í‚¹‚é
            GameObject Dummy = Instantiate(m_Bullet, m_Muzzle.position, m_Muzzle.rotation);
            //’e‚É•¨—‚ª‚È‚¢ê‡A’e‚É•¨—‚ğ‘ã“ü
            if (!Dummy.GetComponent<Rigidbody>())
                Dummy.AddComponent<Rigidbody>();
            //’e‚Ì³–Ê‚ÖŒü‚©‚Á‚ÄA‰Î—Í10000‚ÅËo‚·‚é
            Dummy.GetComponent<Rigidbody>().AddForce(Dummy.transform.forward * 10000.0f);
            //’e‚Í5•bŒã‚É©“®Á–Å‚·‚é(—\–ñ)
            Destroy(Dummy,5.0f);
        }
    }
}
